---
version: "3.8"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    volumes:
      - ./conf/traefik:/etc/traefik:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - certificates:/letsencrypt:rw
    command:
      # Traefik
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--global.sendAnonymousUsage=false"
      # Docker provider
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # SSL resolvers
      - "--certificatesresolvers.ssl.acme.httpchallenge=true"
      - "--certificatesresolvers.ssl.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.ssl.acme.storage=/letsencrypt.acme.json"

    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:9001:8080"

  gallery:
    image: httpd:alpine
    container_name: gallery
    restart: unless-stopped
    volumes: [./gallery/www:/usr/local/apache2/htdocs]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gallery.rule=Host(`kike.wtf`,`www.kike.wtf`) && Method(`GET`)"
      - "traefik.http.routers.gallery.entrypoints=websecure"
      - "traefik.http.routers.gallery.tls=true"
      - "traefik.http.routers.gallery.tls.certresolver=ssl"

volumes:
  certificates: {}
