---
version: "3.8"

services:
  traefik:
    image: traefik:latest
    networks: [proxy]
    container_name: traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./conf:/etc/traefik/dynamic:ro
      - certificates:/letsencrypt:rw
    ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:9001:8080'
    command:
      # Traefik
      - '--log.level=INFO'
      - '--api.insecure=true'
      - '--global.checkNewVersion=true'
      - '--global.sendAnonymousUsage=false'
      # Docker provider
      - '--providers.docker=true'
      - '--providers.docker.watch=true'
      - '--providers.docker.exposedbydefault=false'
      # File provider
      - '--providers.file=true'
      - '--providers.file.directory=/etc/traefik/dynamic'
      - '--providers.file.watch=true'
      # Entrypoints
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      # SSL resolvers
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web'
      - '--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json'

  kikewtf:
    image: httpd:alpine
    networks: [proxy]
    depends_on: [traefik]
    container_name: kikewtf
    restart: unless-stopped
    volumes: [./root:/usr/local/apache2/htdocs:ro]
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.kikewtf.rule=Host(`kike.wtf`) || Host(`www.kike.wtf`)'
      - 'traefik.http.routers.kikewtf.middlewares=security@file,compression@file,jokes@file'
      - 'traefik.http.routers.kikewtf.entrypoints=websecure'
      - 'traefik.http.routers.kikewtf.tls=true'
      - 'traefik.http.routers.kikewtf.tls.certresolver=letsencrypt'

  example:
    image: httpd:alpine
    networks: [proxy]
    depends_on: [traefik]
    container_name: example
    restart: unless-stopped
    volumes:
      - ./example/www:/usr/local/apache2/htdocs:ro
      - ./example/scripts/patch.sh:/docker-entrypoint.d/patch.sh:ro
    entrypoint: ['/bin/sh', '-c', '/bin/sh /docker-entrypoint.d/patch.sh && /usr/local/bin/httpd-foreground']
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.example.rule=Host(`example.kike.wtf`) && Method(`GET`)'
      - 'traefik.http.routers.example.entrypoints=websecure'
      - 'traefik.http.routers.example.middlewares=security@file,compression@file,jokes@file'
      - 'traefik.http.routers.example.tls=true'
      - 'traefik.http.routers.example.tls.certresolver=letsencrypt'

volumes:
  certificates: {}

networks:
  proxy: {}