---
version: "3.8"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - certificates:/letsencrypt:rw
    command:
      # Traefik
      - '--log.level=INFO'
      - '--api.insecure=true'
      - '--global.checkNewVersion=true'
      - '--global.sendAnonymousUsage=false'
      # Docker provider
      - '--providers.docker=true'
      - '--providers.docker.watch=true'
      - '--providers.docker.exposedbydefault=false'
      # Entrypoints
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      # SSL resolvers
      - '--certificatesresolvers.ssl.acme.httpchallenge=true'
      - '--certificatesresolvers.ssl.acme.httpchallenge.entrypoint=web'
      - '--certificatesresolvers.ssl.acme.storage=/letsencrypt.acme.json'
    labels:
      # Middlewares (redirect to https)
      - "traefik.http.middlewares.https-only.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-only.redirectscheme.permanent=true"
      - "traefik.http.middlewares.https-only.redirectscheme.port=443"
      - "traefik.http.middlewares.https-only.headers.forcestsheader=true"
      - "traefik.http.middlewares.https-only.headers.stspreload=true"
      - "traefik.http.middlewares.https-only.headers.stsseconds=315360000"
      - "traefik.http.middlewares.https-only.headers.stsincludesubdomains=true"
      # Middlewares (compression)
      - "traefik.http.middlewares.compression.compress=true"
      - "traefik.http.middlewares.compression.compress.minresponsebodybytes=1024"
      - "traefik.http.middlewares.compression.compress.excludedcontenttypes=text/event-stream"
      # Middlewares (jokes)
      - "traefik.http.middlewares.jokes.headers.customresponseheaders.Server='; DROP TABLE users; --"
      - "traefik.http.middlewares.jokes.headers.customresponseheaders.X-PoweredBy=Pumas, unicorns and rainbows"
      - "traefik.http.middlewares.jokes.headers.customresponseheaders.X-NaNaNaNaNaNaNaNa=Batman!"
      - "traefik.http.middlewares.jokes.headers.customresponseheaders.X-Clacks-Overhead=GNU Kike Fontan"
      # Middlewares (chains)
      - "traefik.http.middlewares.security.chain.middlewares=https-only"


    ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:9001:8080'

  gallery:
    image: httpd:alpine
    depends_on: [traefik]
    container_name: gallery
    restart: unless-stopped
    volumes: [./gallery:/usr/local/apache2/htdocs:ro]
    environment:
      - DOMAIN: ${DOMAIN:-kike.wtf}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.gallery.rule=(Host(`www.{{ env "DOMAIN" }}`) || Host(`{{ env "DOMAIN" }}`)) && PathPrefix(`/gallery/`) && Method(`GET`)'
      - 'traefik.http.middlewares.prefix-gallery.stripprefix.prefixes=/gallery'
      - 'traefik.http.middlewares.prefix-gallery.stripprefix.forceSlash=false'
      - 'traefik.http.routers.gallery.middlewares=prefix-gallery@docker'
      - 'traefik.http.routers.gallery.entrypoints=websecure'
      - 'traefik.http.routers.gallery.tls=true'
      - 'traefik.http.routers.gallery.tls.certresolver=ssl'

volumes:
  certificates: {}
