---
http:
  middlewares:
    security:
      chain:
        middlewares:
          - security-headers@file
          - https-only@file

    https-only:
      chain:
        middlewares:
          - https-redirect@file
          - hsts@file