---
http:
  middlewares:
    jokes:
      headers:
        customResponseHeaders:
          Server: "'; DROP TABLE users; -- --"
          X-PoweredBy: Pumas, unicorns and rainbows
          X-NaNaNaNaNaNaNaNa: Batman!
          X-Clacks-Overhead: GNU Kike Fontan