name: Create the bundle

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      # Create the bundle directory
      - name: Create a new bundle directory
        run: mkdir -p bundle
      - name: Add the root files to the bundle
        run: mv docker-compose.yml conf/ bundle/

      # Compile the 'Example' project
      - name: Add the project to the bundle
        run: mkdir -p ../bundle/example && mv www/ scripts/ ../bundle/example/
        working-directory: example

      # Compile the 'Gallery' project
      - name: Install the dependencies
        run: npm install
        working-directory: gallery
      - name: Lint and format the code
        run: npm run lint && npm run format
        working-directory: gallery
      - name: Build the project
        run: npm run build
        working-directory: gallery
      - name: Add the built project to the bundle
        run: mv www/ ../bundle/gallery/
        working-directory: gallery

      # Release the bundle as an artifact
      - name: Upload the compressed archive to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: kike.wtf
          path: bundle
          if-no-files-found: error
